MP-2543. Deposit cap improvement
mars-protocol/contracts pull request #425
Opened 2024-07-19 10:09 UTC by piobab

Deposit cap check ommited if amount after TX <= before TX for Swap and ProvideLiquidity.

2024-07-22 13:07 UTC, bobthebuidlr requested changes

2024-07-22 13:07 UTC, bobthebuidlr commented on contracts/credit-manager/src/deposit.rs
> +pub fn update_denom_deposits(
I think `update_cap_comparison_amt_for_denom` is a better fit, or at least something along those lines

2024-07-22 13:07 UTC, bobthebuidlr commented on contracts/credit-manager/tests/tests/test_deposit_cap.rs
>  fn asserting_deposit_cap(
I think it would be good to add a test for just `ProvideLiquidity` where we're not depositing the assets prior. Just to test that a decrease in exceeded deposit cap is allowed.

2024-07-22 13:52 UTC, piobab commented on contracts/credit-manager/src/deposit.rs
> +    // Overwrite the previous amount for Deposit action.
We are. `update_denom_deposits` can be executed many times for the same denom. Whenever there is Deposit action it overrides previous value.

2024-07-22 13:52 UTC, piobab commented on contracts/credit-manager/src/deposit.rs
> +    // and withdraw them at the end (resulting in zero net inflow), temporary funds
Yes, but if you deposit denom which has exceeded cap, withdraw the denom, the tx will fail.

2024-07-22 13:52 UTC, piobab commented on contracts/credit-manager/src/deposit.rs
> +    // so we need to subtract it from the total deposit amount to see previous state.
If you execute TX where you send funds/coins the contract balance already increased so if we want to know the original state before the TX we have to subtract sent coins.

2024-07-22 13:52 UTC, piobab commented on contracts/credit-manager/src/execute.rs
>                  // check the deposit cap of the deposited denom
Updated old comments

2024-07-22 13:52 UTC, piobab commented on contracts/credit-manager/tests/tests/test_deposit_cap.rs
>  fn asserting_deposit_cap(
This test case does this. The rest of `Deposit` actions relate to different denoms.

2024-07-22 13:52 UTC, piobab commented on contracts/credit-manager/src/deposit.rs
> +pub fn update_denom_deposits(
Updated to more proper name. Consulted with GPT :)

2024-07-22 13:52 UTC, piobab commented on contracts/credit-manager/src/execute.rs
>      // result of any action. We invoke the AssertDepositCaps callback in the end
Updated

2024-07-22 13:52 UTC, piobab commented on contracts/credit-manager/src/execute.rs
> +    let mut denoms_for_cap_check: BTreeMap<String, Option<Uint128>> = BTreeMap::new();
Added

2024-07-23 09:57 UTC, bobthebuidlr approved these changes

2024-07-25 13:42 UTC, dancreee approved these changes

2024-07-25 13:42 UTC, dancreee commented on contracts/credit-manager/src/deposit.rs
> +    // Check if denom is already in the list
my initial assumption was that this block just reduced unnecessary computation (querying asset params and total deposits etc) on further actions

But it's actually needed also so that a deposit action (which doesn't have an amount associated with it) is not overwritten by a swap action right? Might be worth added a comment or making this more explicit somehow so future maintainers understand

2024-07-25 14:29 UTC, piobab commented on contracts/credit-manager/src/deposit.rs
> +    denom_deposits: BTreeMap<String, Option<Uint128>>,
Maintains keys in sorted order, which means you can iterate over the map in key order.

2024-07-25 14:38 UTC, piobab commented on contracts/credit-manager/src/deposit.rs
> +    // Check if denom is already in the list
Updated the comment:
```
    // Check if the denomination is already in the list.
    // This ensures that a Deposit action (which does not have an associated amount)
    // is not overwritten by a subsequent Swap or ProvideLiquidity action.
    // By confirming the existence of the denomination in the list, we maintain
    // the integrity of the original Deposit action.
```

2024-07-25 15:08 UTC, merged