Clean incentives state when users unstake
mars-protocol/contracts pull request #436
Opened 2024-10-10 08:12 UTC by markonmars

When users unstake from Astroport via Mars incentives contract, we should clean up the state if the user has no more positions.

We should also do the same if the denom has no positions (i.e TOTAL_STAKED_LP = 0)

2024-10-10 10:10 UTC, piobab requested changes

2024-10-10 10:10 UTC, piobab commented on contracts/incentives/src/astro_incentives.rs
> +        let keys_to_remove: Vec<String> =
Better to raise error for a key (not filter out)...

I would use:
`let keys_to_remove: StdResult<Vec<String>> = prefix.keys(store, None, None, Order::Ascending).collect();`
or
`let keys_to_remove = prefix.keys(store, None, None, Order::Ascending).collect::<StdResult<Vec<String>>>()?;`

2024-10-10 10:10 UTC, piobab commented on contracts/incentives/src/astro_incentives.rs
> +        let keys_to_remove: Vec<_> =
Same here. See comment for line 265

2024-10-10 10:11 UTC, piobab commented
@markonmars remember about this one:
![telegram-cloud-photo-size-4-5776364201894331878-y](https://github.com/user-attachments/assets/050df42a-4419-4f1f-a4f6-f21278317eb3)

2024-10-15 06:18 UTC, markonmars commented
closing, replaced with https://github.com/mars-protocol/contracts/pull/437

2024-10-15 06:18 UTC, closed without merging